;;;; -*- Mode:Common-Lisp; Package:GBBOPEN-TOOLS; Syntax:common-lisp -*-
;;;; *-* File: /usr/local/gbbopen/source/tools/test/double-metaphone-test.lisp *-*
;;;; *-* Edited-By: cork *-*
;;;; *-* Last-Edit: Mon Feb 15 14:40:52 2010 *-*
;;;; *-* Machine: cyclone.cs.umass.edu *-*

;;;; **************************************************************************
;;;; **************************************************************************
;;;; *
;;;; *                         Double Metaphone Test
;;;; *
;;;; **************************************************************************
;;;; **************************************************************************

(in-package :gbbopen-tools)

;;; ---------------------------------------------------------------------------

(defparameter *encodings*
    '(("TSTN" "testing")
      ("0" "the")
      ("KK" "quick")
      ("BRN" "brown")
      ("FKS" "fox")
      ("JMPT" "jumped")
      ("AFR" "over")
      ("LS" "lazy")
      ("TKS" "dogs")
      ("MKFR" "MacCafferey")
      ("STFN" "Stephan")
      ("KSSK" "Kuczewski")
      ("TSTN" "testing")
      ;; secondary keys
      (nil "testing" :secondary)
      ("T" "the" :secondary)
      (nil "quick" :secondary)
      (nil "brown" :secondary)
      (nil "fox" :secondary)
      ("AMPT" "jumped" :secondary)
      (nil "over" :secondary)
      (nil "lazy" :secondary)
      (nil "dogs" :secondary)
      (nil "MacCafferey" :secondary)
      (nil "Stephan" :secondary)
      (nil "Kutchefski" :secondary)))

;;; ---------------------------------------------------------------------------

(defparameter *basic-matches*
    '(("Arnow" "Arnoff")
      ("breaux" "brow")
      ("gnu" "new")
      ("thumb" "them")
      ("Uomo" "Womo")
      ("Wasserman" "Vasserman")
      ("Xavier" "savior")))

;;; ---------------------------------------------------------------------------

(defparameter *more-matches*
    '(("Accosinly" "Occasionally")
      ("Ciculer" "Circler")
      ("Circue" "Circle")
      ("Maddness" "Madness")
      ("Occusionaly" "Occasionally")
      ("Steffen" "Stephen")
      ("Thw" "The")
      ("Unformanlly" "Unfortunately")
      ("Unfortally" "Unfortunately")
      ("abilitey" "ability")
      ("abouy" "about")
      ("absorbtion" "absorption")
      ("accidently" "accidentally")
      ("accomodate" "accommodate")
      ("acommadate" "accommodate")
      ("acord" "accord")
      ("adultry" "adultery")
      ("aggresive" "aggressive")
      ("alchohol" "alcohol")
      ("alchoholic" "alcoholic")
      ("allieve" "alive")
      ("alot" "a lot")
      ("alright" "all right")
      ("amature" "amateur")
      ("ambivilant" "ambivalent")
      ("amification" "amplification")
      ("amourfous" "amorphous")
      ("annoint" "anoint")
      ("annonsment" "announcement")
      ("annoyting" "anting")
      ("annuncio" "announce")
      ("anonomy" "anatomy")
      ("anotomy" "anatomy")
      ("antidesestablishmentarianism" "antidisestablishmentarianism")
      ("antidisestablishmentarism" "antidisestablishmentarianism")
      ("anynomous" "anonymous")
      ("appelet" "applet")
      ("appreceiated" "appreciated")
      ("appresteate" "appreciate")
      ("aquantance" "acquaintance")
      ("aratictature" "architecture")
      ("archeype" "archetype")
      ("aricticure" "architecture")
      ("artic" "arctic")
      ("asentote" "asymptote")
      ("ast" "at")
      ("asterick" "asterisk")
      ("asymetric" "asymmetric")
      ("atentively" "attentively")
      ("autoamlly" "automatically")
      ("bankrot" "bankrupt")
      ("basicly" "basically")
      ("batallion" "battalion")
      ("bbrose" "browse")
      ("beauro" "bureau")
      ("beaurocracy" "bureaucracy")
      ("beggining" "beginning")
      ("beging" "beginning")
      ("behaviour" "behavior")
      ("beleive" "believe")
      ("belive" "believe")
      ("benidifs" "benefits")
      ("bigginging" "beginning")
      ("blait" "bleat")
      ("bouyant" "buoyant")
      ("boygot" "boycott")
      ("brocolli" "broccoli")
      ("buch" "bush")
      ("buder" "butter")
      ("budr" "butter")
      ("budter" "butter")
      ("buracracy" "bureaucracy")
      ("burracracy" "bureaucracy")
      ("buton" "button")
      ("byby" "by by")
      ("cauler" "caller")
      ("ceasar" "caesar")
      ("cemetary" "cemetery")
      ("changeing" "changing")
      ("cheet" "cheat")
      ("cicle" "circle")
      ("cimplicity" "simplicity")
      ("circumstaces" "circumstances")
      ("clob" "club")
      ("coaln" "colon")
      ("cocamena" "cockamamie")
      ("colleaque" "colleague")
      ("colloquilism" "colloquialism")
      ("columne" "column")
      ("comiler" "compiler")
      ("comitmment" "commitment")
      ("comitte" "committee")
      ("comittmen" "commitment")
      ("comittmend" "commitment")
      ("commerciasl" "commercials")
      ("commited" "committed")
      ("commitee" "committee")
      ("companys" "companies")
      ("compicated" "complicated")
      ("comupter" "computer")
      ("concensus" "consensus")
      ("confusionism" "confucianism")
      ("congradulations" "congratulations")
      ("conibation" "contribution")
      ("consident" "consistent")
      ("consident" "consonant")
      ("contast" "constant")
      ("contastant" "constant")
      ("contunie" "continue")
      ("cooly" "coolly")
      ("copping" "coping")
      ("cosmoplyton" "cosmopolitan")
      ("courst" "court")
      ("crasy" "crazy")
      ("cravets" "caveats")
      ("credetability" "credibility")
      ("criqitue" "critique")
      ("croke" "croak")
      ("crucifiction" "crucifixion")
      ("crusifed" "crucified")
      ("ctitique" "critique")
      ("cumba" "combo")
      ("custamisation" "customization")
      ("dag" "dog")
      ("daly" "daily")
      ("danguages" "dangerous")
      ("deaft" "draft")
      ("defence" "defense")
      ("defenly" "defiantly")
      ("definate" "definite")
      ("definately" "definitely")
      ("dependeble" "dependable")
      ("descrption" "description")
      ("descrptn" "description")
      ("desparate" "desperate")
      ("dessicate" "desiccate")
      ("destint" "distant")
      ("develepment" "developments")
      ("developement" "development")
      ("develpond" "development")
      ("devulge" "divulge")
      ("diagree" "disagree")
      ("dieties" "deities")
      ("dinasaur" "dinosaur")
      ("dinasour" "dinosaur")
      ("direcyly" "directly")
      ("discuess" "discuss")
      ("disect" "dissect")
      ("disippate" "dissipate")
      ("disition" "decision")
      ("dispair" "despair")
      ("disssicion" "discussion")
      ("distarct" "distract")
      ("distart" "distort")
      ("distroy" "destroy")
      ("documtations" "documentation")
      ("doenload" "download")
      ("dongle" "dangle")
      ("doog" "dog")
      ("dramaticly" "dramatically")
      ("drunkeness" "drunkenness")
      ("ductioneery" "dictionary")
      ("dur" "due")
      ("duren" "during")
      ("dymatic" "dynamic")
      ("dynaic" "dynamic")
      ("ecstacy" "ecstasy")
      ("efficat" "efficient")
      ("efficity" "efficacy")
      ("effots" "efforts")
      ("egsistence" "existence")
      ("eitiology" "etiology")
      ("elagent" "elegant")
      ("elligit" "elegant")
      ("embarass" "embarrass")
      ("embarassment" "embarrassment")
      ("embaress" "embarrass")
      ("encapsualtion" "encapsulation")
      ("encyclapidia" "encyclopedia")
      ("encyclopia" "encyclopedia")
      ("engins" "engine")
      ("enhence" "enhance")
      ("enligtment" "Enlightenment")
      ("ennuui" "ennui")
      ("enought" "enough")
      ("enventions" "inventions")
      ("envireminakl" "environmental")
      ("enviroment" "environment")
      ("epitomy" "epitome")
      ("equire" "acquire")
      ("errara" "error")
      ("erro" "error")
      ("evaualtion" "evaluation")
      ("evething" "everything")
      ("evtually" "eventually")
      ("excede" "exceed")
      ("excercise" "exercise")
      ("excpt" "except")
      ("excution" "execution")
      ("exhileration" "exhilaration")
      ("existance" "existence")
      ("expleyly" "explicitly")
      ("explity" "explicitly")
      ("expresso" "espresso")
      ("exspidient" "expedient")
      ("extions" "extensions")
      ("factontion" "factorization")
      ("failer" "failure")
      ("famdasy" "fantasy")
      ("faver" "favor")
      ("faxe" "fax")
      ("febuary" "february")
      ("firey" "fiery")
      ("fistival" "festival")
      ("flatterring" "flattering")
      ("fluk" "flux")
      ("flukse" "flux")
      ("fone" "phone")
      ("forsee" "foresee")
      ("frustartaion" "frustrating")
      ("fuction" "function")
      ("funetik" "phonetic")
      ("futs" "guts")
      ("gamne" "came")
      ("gaurd" "guard")
      ("generly" "generally")
      ("ghandi" "gandhi")
      ("goberment" "government")
      ("gobernement" "government")
      ("gobernment" "government")
      ("gotton" "gotten")
      ("gracefull" "graceful")
      ("gradualy" "gradually")
      ("grammer" "grammar")
      ("hallo" "hello")
      ("hapily" "happily")
      ("harrass" "harass")
      ("havne" "have")
      ("heellp" "help")
      ("heighth" "height")
      ("hellp" "help")
      ("helo" "hello")
      ("herlo" "hello")
      ("hifin" "hyphen")
      ("hifine" "hyphen")
      ("higer" "higher")
      ("hiphine" "hyphen")
      ("hippie" "hippy")
      ("hippopotamous" "hippopotamus")
      ("hlp" "help")
      ("hourse" "horse")
      ("houssing" "housing")
      ("howaver" "however")
      ("howver" "however")
      ("humaniti" "humanity")
      ("hyfin" "hyphen")
      ("hypotathes" "hypothesis")
      ("hypotathese" "hypothesis")
      ("hystrical" "hysterical")
      ("ident" "indent")
      ("illegitament" "illegitimate")
      ("imbed" "embed")
      ("imediaetly" "immediately")
      ("imfamy" "infamy")
      ("immenant" "immanent")
      ("implemtes" "implements")
      ("inadvertant" "inadvertent")
      ("incase" "in case")
      ("incedious" "insidious")
      ("incompleet" "incomplete")
      ("incomplot" "incomplete")
      ("inconvenant" "inconvenient")
      ("inconvience" "inconvenience")
      ("independant" "independent")
      ("independenent" "independent")
      ("indepnends" "independent")
      ("indepth" "in depth")
      ("indispensible" "indispensable")
      ("inefficite" "inefficient")
      ("inerface" "interface")
      ("infact" "in fact")
      ("influencial" "influential")
      ("inital" "initial")
      ("initinized" "initialized")
      ("initized" "initialized")
      ("innoculate" "inoculate")
      ("insistant" "insistent")
      ("insistenet" "insistent")
      ("instulation" "installation")
      ("intealignt" "intelligent")
      ("intejilent" "intelligent")
      ("intelegent" "intelligent")
      ("intelegnent" "intelligent")
      ("intelejent" "intelligent")
      ("inteligent" "intelligent")
      ("intelignt" "intelligent")
      ("intellagant" "intelligent")
      ("intellegent" "intelligent")
      ("intellegint" "intelligent")
      ("intellgnt" "intelligent")
      ("intensionality" "intensionally")
      ("interate" "iterate")
      ("internation" "international")
      ("interpretate" "interpret")
      ("interpretter" "interpreter")
      ("intertes" "interested")
      ("intertesd" "interested")
      ("invermeantial" "environmental")
      ("irregardless" "regardless")
      ("irresistable" "irresistible")
      ("irritible" "irritable")
      ("islams" "muslims")
      ("isotrop" "isotope")
      ("isreal" "israel")
      ("johhn" "john")
      ("judgement" "judgment")
      ("kippur" "kipper")
      ("knawing" "knowing")
      ("latext" "latest")
      ("leasve" "leave")
      ("lesure" "leisure")
      ("liasion" "lesion")
      ("liason" "liaison")
      ("libary" "library")
      ("likly" "likely")
      ("lilometer" "kilometer")
      ("liquify" "liquefy")
      ("lloyer" "layer")
      ("lossing" "losing")
      ("luser" "laser")
      ("maintanence" "maintenance")
      ("majaerly" "majority")
      ("majoraly" "majority")
      ("maks" "masks")
      ("mandelbrot" "Mandelbrot")
      ("mant" "want")
      ("marshall" "marshal")
      ("maxium" "maximum")
      ("meory" "memory")
      ("metter" "better")
      ("mic" "mike")
      ("midia" "media")
      ("millenium" "millennium")
      ("miniscule" "minuscule")
      ("minkay" "monkey")
      ("minum" "minimum")
      ("mischievious" "mischievous")
      ("misilous" "miscellaneous")
      ("momento" "memento")
      ("monkay" "monkey")
      ("mosaik" "mosaic")
      ("mostlikely" "most likely")
      ("mousr" "mouser")
      ("mroe" "more")
      ("neccessary" "necessary")
      ("necesary" "necessary")
      ("necesser" "necessary")
      ("neice" "niece")
      ("neighbour" "neighbor")
      ("nemonic" "pneumonic")
      ("nevade" "Nevada")
      ("nickleodeon" "nickelodeon")
      ("nieve" "naive")
      ("noone" "no one")
      ("noticably" "noticeably")
      ("notin" "not in")
      ("nozled" "nuzzled")
      ("objectsion" "objects")
      ("obsfuscate" "obfuscate")
      ("ocassion" "occasion")
      ("occuppied" "occupied")
      ("occurence" "occurrence")
      ("octagenarian" "octogenarian")
      ("olf" "old")
      ("opposim" "opossum")
      ("organise" "organize")
      ("organiz" "organize")
      ("orientate" "orient")
      ("oscilascope" "oscilloscope")
      ("oving" "moving")
      ("paramers" "parameters")
      ("parametic" "parameter")
      ("paranets" "parameters")
      ("partrucal" "particular")
      ("pataphysical" "metaphysical")
      ("patten" "pattern")
      ("permissable" "permissible")
      ("permition" "permission")
      ("permmasivie" "permissive")
      ("perogative" "prerogative")
      ("persue" "pursue")
      ("phantasia" "fantasia")
      ("phenominal" "phenomenal")
      ("picaresque" "picturesque")
      ("playwrite" "playwright")
      ("poeses" "poesies")
      ("polation" "politician")
      ("poligamy" "polygamy")
      ("politict" "politic")
      ("pollice" "police")
      ("polypropalene" "polypropylene")
      ("pompom" "pompon")
      ("possable" "possible")
      ("practicle" "practical")
      ("pragmaticism" "pragmatism")
      ("preceeding" "preceding")
      ("precion" "precision")
      ("precios" "precision")
      ("preemptory" "peremptory")
      ("prefices" "prefixes")
      ("prefixt" "prefixed")
      ("presbyterian" "Presbyterian")
      ("presue" "pursue")
      ("presued" "pursued")
      ("privielage" "privilege")
      ("priviledge" "privilege")
      ("proceedures" "procedures")
      ("pronensiation" "pronunciation")
      ("pronisation" "pronunciation")
      ("pronounciation" "pronunciation")
      ("properally" "properly")
      ("proplematic" "problematic")
      ("protray" "portray")
      ("pscolgst" "psychologist")
      ("psicolagest" "psychologist")
      ("psycolagest" "psychologist")
      ("quoz" "quiz")
      ("radious" "radius")
      ("ramplily" "rampantly")
      ("reccomend" "recommend")
      ("reccona" "raccoon")
      ("recieve" "receive")
      ("reconise" "recognize")
      ("rectangeles" "rectangle")
      ("redign" "redesign")
      ("reoccurring" "recurring")
      ("repitition" "repetition")
      ("replasments" "replacement")
      ("reposable" "responsible")
      ("reseblence" "resemblance")
      ("respct" "respect")
      ("respecally" "respectfully")
      ("roon" "room")
      ("rought" "roughly")
      ("rsx" "RSX")
      ("rudemtry" "rudimentary")
      ("runnung" "running")
      ("sacreligious" "sacrilegious")
      ("saftly" "safely")
      ("salut" "salute")
      ("satifly" "satisfy")
      ("scrabdle" "scrabble")
      ("searcheable" "searchable")
      ("secion" "section")
      ("seferal" "several")
      ("segements" "segments")
      ("sence" "sense")
      ("seperate" "separate")
      ("sherbert" "sherbet")
      ("sicolagest" "psychologist")
      ("sieze" "seize")
      ("simpfilty" "simplicity")
      ("simplye" "simply")
      ("singal" "signal")
      ("sitte" "site")
      ("situration" "situation")
      ("slyph" "sylph")
      ("smil" "smile")
      ("snuck" "sneaked")
      ("sometmes" "sometimes")
      ("soonec" "sonic")
      ("specificialy" "specifically")
      ("spel" "spell")
      ("spoak" "spoke")
      ("sponsered" "sponsored")
      ("stering" "steering")
      ("straightjacket" "straitjacket")
      ("stumach" "stomach")
      ("stutent" "student")
      ("styleguide" "style guide")
      ("subisitions" "substitutions")
      ("subjecribed" "subscribed")
      ("subpena" "subpoena")
      ("substations" "substitutions")
      ("suger" "sugar")
      ("supercede" "supersede")
      ("superfulous" "superfluous")
      ("susan" "Susan")
      ("swimwear" "swim wear")
      ("syncorization" "synchronization")
      ("taff" "tough")
      ("taht" "that")
      ("tattos" "tattoos")
      ("techniquely" "technically")
      ("teh" "the")
      ("tem" "team")
      ("teo" "two")
      ("teridical" "theoretical")
      ("tesst" "test")
      ("tets" "tests")
      ("thanot" "than or")
      ("theirselves" "themselves")
      ("theridically" "theoretical")
      ("thredically" "theoretically")
      ("thruout" "throughout")
      ("ths" "this")
      ("titalate" "titillate")
      ("tobagan" "tobaggon")
      ("tommorrow" "tomorrow")
      ("tomorow" "tomorrow")
      ("tradegy" "tragedy")
      ("trubbel" "trouble")
      ("ttest" "test")
      ("tunnellike" "tunnel like")
      ("tured" "turned")
      ("tyrrany" "tyranny")
      ("unatourral" "unnatural")
      ("unaturral" "unnatural")
      ("unconisitional" "unconstitutional")
      ("unconscience" "unconscious")
      ("underladder" "under ladder")
      ("unentelegible" "unintelligible")
      ("unfortunently" "unfortunately")
      ("unnaturral" "unnatural")
      ("upcast" "up cast")
      ("upmost" "utmost")
      ("uranisium" "uranium")
      ("verison" "version")
      ("vinagarette" "vinaigrette")
      ("volumptuous" "voluptuous")
      ("volunteerism" "voluntarism")
      ("volye" "volley")
      ("wadting" "wasting")
      ("waite" "wait")
      ("wan't" "won't")
      ("warloord" "warlord")
      ("whaaat" "what")
      ("whard" "ward")
      ("whimp" "wimp")
      ("wicken" "weaken")
      ("wierd" "weird")
      ("wrank" "rank")
      ("writeen" "righten")
      ("writting" "writing")
      ("wundeews" "windows")
      ("yeild" "yield")
      ("youe" "your")))

;;; ---------------------------------------------------------------------------

(defun report-problem (&rest args)
  (declare (dynamic-extent args))
  (apply #'format t "~&;;     ~@?" args))	   

;;; ---------------------------------------------------------------------------

(defun check-encodings ()
  (format t "~&;;   Starting encodings test...~%")
  (loop for (expected string secondary-p) in *encodings* do
        (multiple-value-bind (primary secondary)
            (double-metaphone string)
	  (cond 
	   (secondary-p
	    (unless (string= secondary expected)
	      (report-problem "Secondary of ~s should be ~s, got ~s"
			      string expected secondary)))
	   (t (unless (string= primary expected)
		(report-problem "Primary of ~s should be ~s, got ~s"
				string expected primary))))))
  (format t "~&;;   Encodings test completed.~%"))

;;; ---------------------------------------------------------------------------

(defun check-the-matches (matches label summarize-p)
  (format t "~&;;   Starting ~a matches test~@[ (summarizing)~]...~%" 
	  label
	  summarize-p)
  (let ((total-count 0)
	(strong-match-count 0)
	(normal-match-count 0)
	(weak-match-count 0)
	(failure-count 0))
    (loop for (string1 string2) in matches do
	  (incf& total-count)
	  (multiple-value-bind (primary1 secondary1)
	      (double-metaphone string1)
	    (multiple-value-bind (primary2 secondary2)
		(double-metaphone string2)
	      (unless (or
		       ;; Strong match:
		       (when (string= primary1 primary2)
			 (incf& strong-match-count))
		       ;; Normal matches:
		       (when (or (and secondary2 (string= primary1 secondary2))
				 (and secondary1 (string= secondary1 primary2)))
			 (incf& normal-match-count))
		       ;; Weak match:
		       (when (and secondary1 
				  secondary2 
				  (string= secondary1 secondary2))
			 (incf& weak-match-count)))
		(incf& failure-count)
		(unless summarize-p
		  (report-problem
		   "Match of ~s and ~s failed (~s~@[;~s~] ~s~@[;~s~])."
		   string1 string2 
		   primary1 secondary1
		   primary2 secondary2))))))
    (format t "~&;;   ~@(~a matches~) test completed (~s/~s S:~s N:~s W:~s).~%"
	    label
	    (-& total-count failure-count)
	    total-count
	    strong-match-count
	    normal-match-count
	    weak-match-count)))

;;; ---------------------------------------------------------------------------

(defun check-basic-matches (&optional summarize-p)
  (check-the-matches *basic-matches* "basic" summarize-p))

(defun check-more-matches (&optional summarize-p)
  (check-the-matches *more-matches* "more" summarize-p))

;;; ---------------------------------------------------------------------------

(defun double-metaphone-tests ()
  (format t "~&;; Starting double-metaphone tests...~%")
  (check-encodings)
  (check-basic-matches 't)
  (check-more-matches 't)
  (format t "~&;; Double-metaphone tests completed.~%"))

;;; ---------------------------------------------------------------------------

(when *autorun-modules* 
  (double-metaphone-tests))

;;; ===========================================================================
;;;                               End of File
;;; ===========================================================================
